# Enable mouse support
set -g mouse on

# start the page number on 1 instead of 0 which is the default
set -g base-index 1
set -g pane-base-index 1
# when closing a pane should trigger reodering of page id number so they always are in order
set -g renumber-windows on

# set scroll history to 100,000 lines
set-option -g history-limit 100000

# modern colors
# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",alacritty:Tc"

# unbind the prefix and bind it to Ctrl-s (not ^a since that is main tmux)
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Unbind + Rebind window splits
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind Enter split-window -v -c "#{pane_current_path}"

# Avoid ESC delay
set -s escape-time 0

# Fix titlebar
set -g set-titles on
set -g set-titles-string "#T"

# VIM mode
set -g mode-keys vi

# Move between panes with vi keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Bind r to reload tmux config
unbind k
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded 🚀"

######################
### DESIGN CHANGES ###
######################

set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'latte' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"

# set-hook -g client-dark-theme {
#   set -g @catppuccin_flavor "frappe"
#   set -g @catppuccin_reset "true"
#
#   # NOTE: you may need to set more `@catppuccin_*` variables to fully reset
#   # everything.
#
#   run ~/code/github.com/catppuccin/tmux/catppuccin.tmux
# }
# set-hook -g client-light-theme {
#   set -g @catppuccin_flavor "latte"
#   set -g @catppuccin_reset "true"
#
#   # NOTE: you may need to set more `@catppuccin_*` variables to fully reset
#   # everything.
#
#   run ~/code/github.com/catppuccin/tmux/catppuccin.tmux
# }
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Colors (gruvbox dark base16)

# default statusbar colors
# but a shade darker to show remote
# set-option -g status-style "fg=#bdae93,bg=#1c1816"

# default window title colors
# set-window-option -g window-status-style "fg=#bdae93,bg=default"

# active window title colors
# set-window-option -g window-status-current-style "fg=#fabd2f,bg=default"

# pane border
# set-option -g pane-border-style "fg=#3c3836"
# set-option -g pane-active-border-style "fg=#504945"

# message text
# set-option -g message-style "fg=#d5c4a1,bg=#3c3836"

# pane number display
# set-option -g display-panes-active-colour "#b8bb26"
# set-option -g display-panes-colour "#fabd2f"

# clock
# set-window-option -g clock-mode-colour "#b8bb26"

# copy mode highligh
# set-window-option -g mode-style "fg=#bdae93,bg=#504945"

# bell
# set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"
